site_name: Louierw Blog

theme:
  name: material

  features:
    - navigation.tabs
    - content.tabs.link
    - navigation.indexes

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

